# Generated by Django 5.2.1 on 2025-05-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
