# Generated by Django 5.2.1 on 2025-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_sellerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerapplication',
            name='address',
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
