# Generated by Django 5.2.1 on 2025-05-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_remove_sellerapplication_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerapplication',
            name='approved',
        ),
    ]
