# Generated by Django 5.2.1 on 2025-05-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_eventcategory_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refundable',
            field=models.BooleanField(default=False, verbose_name='Refundable'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('STANDARD', 'Standard'), ('EARLY_BIRD', 'Early Bird'), ('STUDENT', 'Student'), ('SENIOR', 'Senior'), ('CHILD', 'Child')], default='STANDARD', max_length=20, verbose_name='Ticket Type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transferable',
            field=models.BooleanField(default=False, verbose_name='Transferable'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid From'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Until'),
        ),
    ]
