# Generated by Django 5.2.1 on 2025-05-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_options_ticket_notes_ticket_refundable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='refundable',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='transferable',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='valid_until',
        ),
    ]
