# Generated by Django 5.2.1 on 2025-05-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_eventcategory_description_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_af',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ar_dz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ast',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_be',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_br',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_bs',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ckb',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_cs',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_cy',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_da',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_dsb',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_el',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en_au',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_eo',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es_co',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es_mx',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es_ni',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es_ve',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_et',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_eu',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fy',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ga',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_gd',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_gl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_hr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_hsb',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_hu',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ig',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_io',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_is',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ka',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_kab',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_km',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_kn',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ko',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_lb',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_lt',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_lv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_mk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ml',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_mn',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_mr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ms',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_my',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_nb',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ne',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_nn',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_os',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_pa',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_sk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_sl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_sq',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_sr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_sr_latn',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_te',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_tg',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_th',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_tk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_tt',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_udm',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ug',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ur',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_af',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ar_dz',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ast',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_bn',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_bs',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ckb',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_cs',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_cy',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_da',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_dsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_el',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en_au',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_eo',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_es_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_es_co',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_es_mx',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_es_ni',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_es_ve',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_eu',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_fy',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ga',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_gd',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_gl',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_hr',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_hsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_hu',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ia',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ig',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_io',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_is',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ka',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_kab',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_km',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_kn',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ko',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_lb',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ml',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_mr',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ms',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_my',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_nb',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ne',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_nn',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_os',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_pa',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_sl',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ta',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_te',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_th',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_tt',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_udm',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ug',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ur',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_zh_hant',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_af',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ar_dz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ast',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_bn',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_bs',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ckb',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_cs',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_cy',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_da',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_dsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_el',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_en_au',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_eo',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_es_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_es_co',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_es_mx',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_es_ni',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_es_ve',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_eu',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_fy',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ga',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_gd',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_gl',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_hr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_hsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_hu',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ia',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ig',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_io',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_is',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ka',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_kab',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_km',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_kn',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ko',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_lb',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ml',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_mr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ms',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_my',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_nb',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ne',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_nn',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_os',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_pa',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_sl',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ta',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_te',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_th',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_tt',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_udm',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ug',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ur',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_zh_hant',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_af',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ar_dz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_be',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_bs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ckb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_cs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_da',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_dsb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_el',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_en_au',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_eo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_es_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_es_co',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_es_mx',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_es_ni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_es_ve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_et',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_eu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_fy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_gd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_gl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_hr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_hsb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_hu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_hy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_io',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_is',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_kab',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_km',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_lb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_lv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_mk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_mn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_my',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_nb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_nn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_pa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_sl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_sq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_sr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_sr_latn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_sv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_tg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_tk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_tt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_udm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_vi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ar_dz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ckb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
