# Generated by Django 5.2.1 on 2025-05-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_eventcategory_description_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_az',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_ru',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_used',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('used', 'Used')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='current_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('STANDARD', 'Standard'), ('EARLY_BIRD', 'Early Bird'), ('STUDENT', 'Student'), ('SENIOR', 'Senior'), ('CHILD', 'Child')], default='STANDARD', max_length=20),
        ),
    ]
