# Generated by Django 5.2.1 on 2025-05-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={},
        ),
    ]
